version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: shared_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-notes_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-notes_db}
    ports:
      -"5432:5432"
    volumes:
      -postgres_data:/var/lib/postgresql/data
    restart: always

  notes-service:
    build: ./notesproject/notes-project
    volumes:
      - ./notesproject/src:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME:-notes_db}
      - DB_USER=${DB_USER:-notes_user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  notification-service:
    build: ./notificationService
    volumes:
      - ./notificationService/src:/app
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=postgres
      - DB_NAME=$
  # mongo:
  #   image: mongo:5.0
  #   container_name: shared_mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root} #ifnt set, uses root
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-mongopass}
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   restart: always

  #   notes-service:
  #     build: ./notesproject
  #     volumes:
  #       - ./notesproject/src:/app
  #     ports:
  #       - "8000:8000"
  #     environment:
  #       - DB_HOST=mongo
  #       - DB_NAME=notes_db
  #       - DB_USER=${MONGO_USER:-root}
  #       - DB_PASS=${MONGO_PASSWORD:-mongopass}
  #     depends_on:
  #       - mongo

  #   notification-service:
  #     build: ./notificationService
  #     volumes:
  #       - ./notificationService/src:/app
  #     ports:
  #       - "8001:8001"
  #     environment:
  #       - DB_HOST=mongodb
  #       - DB_NAME=notifications_db
  #       - DB_USER=${MONGO_USER:-root}
  #       - DB_PASS=${MONGO_PASSWORD:-mongopass}
  #     depends_on:
  #       - mongo

  # django:
  #   build: .
  #   command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  #   env_file: .env
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - mongo

volumes:
  postgres_data: