version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"

  backend-django:
    build: ./backend-django
    ports:
      - "8000:8000"
    depends_on:
      - db

  backend-express:
    build: ./backend-express
    ports:
      - "3000:3000"
    depends_on:
      - db

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - backend-django
      - backend-express

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
