version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend-express
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - JWT_SECRET=yourSuperSecretKeyHere
      - MONGO_URI=mongodb+srv://michellelyandry:JK3pGOmSDlFnPo2X@todo-cluster.gnnbwqv.mongodb.net/?retryWrites=true&w=majority&appName=todo-cluster
    depends_on:
      - mongo

volumes:
  mongo_data:
