version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend-express:
    build: ./backend-express
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb+srv://michellelyandry:JK3pGOmSDlFnPo2X@todo-cluster.gnnbwqv.mongodb.net/?retryWrites=true&w=majority&appName=todo-cluster
    depends_on:
      - mongo

 # backend-django:
  #  build: ./backend-django
   # ports:
    #  - "8000:8000"
   # environment:
    #  - MONGO_URI=mongodb://mongo:27017/mydb
   # depends_on:
    #  - mongo #

volumes:
  mongo_data:
