# Generated by Django 5.2.1 on 2025-06-08 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='project.project'),
        ),
        migrations.AlterField(
            model_name='notecollaborator',
            name='permission_level',
            field=models.CharField(choices=[('view', 'Can View'), ('comment', 'Can Comment'), ('edit', 'Can Edit')], default='edit', max_length=20),
        ),
    ]
