# Generated by Django 5.2.1 on 2025-06-08 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_id', models.UUIDField()),
                ('reminder_title', models.CharField(max_length=200)),
                ('reminder_due_date', models.DateTimeField()),
                ('notification_sent', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['reminder_id'], name='notifier_no_reminde_45b48c_idx'), models.Index(fields=['notification_sent'], name='notifier_no_notific_52160f_idx')],
            },
        ),
    ]
